kind: Secret
apiVersion: v1

metadata:
  name: mysql-secret
  namespace: mysql

type: opaque

data:
  password: QWRtaW4xMjM= 


---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: two-tier

type: opaque

data:
  password: QWRtaW4xMjM=
