name: DeveSecOps End To End pipeline

on:
    workflow_dispatch:
    
jobs:
    code-quality:
        uses: ./.github/workflows/code-scan.yml

    # secrets-scan:
    #     uses: ./.github/workflows/secrets-scan.yml
    #     secrets: inherit

    dependency-scan:
        uses: ./.github/workflows/depenency-scam.yml

    dockerfile-scan:
        uses: ./.github/workflows/dockerfile-scan.yml
    
    
