name: DeveSecOps End To End pipeline

on:
    workflow_dispatch:
    
jobs:
    code-quality:
        uses: ./.github/workflows/code-scan.yml

    # secrets-scan:
    #     uses: ./.github/workflows/secrets-scan.yml
    #     secrets: inherit

    dependency-scan:
        uses: ./.github/workflows/depenency-scam.yml

    dockerfile-scan:
        uses: ./.github/workflows/dockerfile-scan.yml

    build:
        needs: [code-quality, dependency-scan, dockerfile-scan]
        uses: ./.github/workflows/prd_cicd.yml
        secrets: inherit
    
    trivy-scan:
        needs: build
        uses: ./.github/workflows/docker-image.yml
        secrets: inherit

    deploy:
        needs: [trivy-scan]
        uses: ./.github/workflows/deploy-server.yml
        secrets: inherit
    
    
