name: Docker scan

on:
    workflow_call:

jobs:
    dockerfile-lint:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v6
            - name: checking Dockerfile Linting
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile
