name: PROD-CICD

on:
    # push:
    #     branches: [dev]
    workflow_call:

    

jobs:
    docker-build-push:
        runs-on: ubuntu-latest
        steps:
            - name: git clone
              uses: actions/checkout@v7
            
            - name: docker login
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }} 

            - name: docker build and push
              uses: docker/build-push-action@v7
              with:
                context: .
                push: true
                tags: ${{ vars.dockerhub_username }}/flask-app:${{ github.sha }}

