name: Scerets scan

on:
    workflow_call

jobs:
    secrets_scan:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v5
              with:
                fetch-depth: 0

            - name: GitLeaks scanning
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
